[package]
name = "krust-manifesto"
version = "0.1.0"
edition = "2021"

[dependencies]
k8s-openapi = { version = "0.20.0", features = ["earliest"], default_features = false }
serde_yaml = "0.9.27"
serde = "1.0.193"
