[package]
name = "krust-manifesto"
version = "0.1.0"
edition = "2021"

[dependencies]
#kube-core = { version = "0.82.2", default_features = false }
k8s-openapi = { version = "0.18.0", features = ["v1_26"], default_features = false }
serde_yaml = "0.9.21"
serde = "1.0.188"
